global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Kafka JMX指标
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9997']
    metrics_path: /metrics
    scrape_interval: 10s

  # Kafka Connect指标
  - job_name: 'kafka-connect'
    static_configs:
      - targets: ['kafka-connect:8083']
    metrics_path: /metrics
    scrape_interval: 10s

  # Node Exporter (可选，用于系统指标)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 10s

  # JMX Exporter for Kafka (如果配置了JMX exporter)
  - job_name: 'kafka-jmx'
    static_configs:
      - targets: ['kafka:7071']
    scrape_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - "alertmanager:9093"

# 告警规则配置
rule_files:
  - "alert_rules.yml" 